export const types = {
    AGREGAR_AL_CARRITO : "AGREGAR_AL_CARRITO",
    QUITAR_UNO_DEL_CARRITO : "QUITAR_DEL_CARRITO",
    QUITAR_TODOS_DEL_CARRITO : "QUITAR_TODOS_DEL_CARRITO",
    LIMPIAR_CARRITO : "LIMPIAR_CARRITO"
}
